"""empty message

Revision ID: fa517ce310ac
Revises: 
Create Date: 2026-02-06 21:51:00.474014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa517ce310ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'language',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(),
               nullable=True)
    op.alter_column('users', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('users_phone_number_key'), 'users', type_='unique')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('longitude', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('latitude', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_phone_number_key'), 'users', ['phone_number'])
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('users', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'language',
               existing_type=sa.String(),
               type_=sa.CHAR(length=2),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
